name: Keyboard Layout Bug Report 🪲
description: Report issues with the Crypto Keyboard layout or its implementation
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Please provide details about any issues with the Crypto Keyboard layout or its implementation.

  - type: markdown
    attributes:
      value: |
        System-specific details.

  - type: input
    id: environment
    attributes:
      label: Environment
      description: Operating system and version
      placeholder: macOS 14.4
    validations:
      required: true

  - type: textarea
    id: bug
    attributes:
      label: Bug Description
      description: Describe the issue with the keyboard layout.
      placeholder: Describe the bug
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior with the keyboard layout.
      placeholder: |
        1. Install keyboard layout...
        2. Press key combination...
        3. Observe...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: Describe what you expected to happen.
      placeholder: Expected result
    validations:
      required: true

  - type: input
    id: commit
    attributes:
      label: Version
      description: Version of the keyboard layout where bug occurs.
      placeholder: v1.0.0

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
